"use strict";
const API_BASE_URL="http://localhost:5000";
const API=`${API_BASE_URL}/api/auth/register`;
const form=document.getElementById("registerForm"), message=document.getElementById("message"), btn=document.getElementById("registerBtn"), btnText=document.getElementById("registerBtnText"), btnIcon=document.getElementById("registerBtnIcon"), password=document.getElementById("password"), confirm=document.getElementById("confirmPassword"), strength=document.getElementById("strength"), toggle=document.getElementById("passwordToggle");
function showMessage(text,type="error"){message.textContent=text;message.className=`message ${type}`;message.hidden=false}
function loading(v){btn.disabled=v;btnText.textContent=v?"Creating Account...":"Create Account";btnIcon.className=v?"fas fa-spinner fa-spin":"fas fa-arrow-right"}
function saveAuth(data){localStorage.setItem("authToken",data.token);localStorage.setItem("authUser",JSON.stringify(data.user))}
function updateStrength(){const p=password.value;let text="Use at least 6 characters.";if(p.length>=6)text="Good password length.";if(p.length>=10&&/[A-Z]/.test(p)&&/[0-9]/.test(p))text="Strong password.";strength.textContent=text}
password.addEventListener("input",updateStrength);
toggle.addEventListener("click",()=>{password.type=password.type==="password"?"text":"password";toggle.querySelector("i").className=password.type==="password"?"fas fa-eye":"fas fa-eye-slash"});
form.addEventListener("submit",async e=>{e.preventDefault();message.hidden=true;const name=document.getElementById("name").value.trim(),email=document.getElementById("email").value.trim().toLowerCase(),p=password.value,c=confirm.value;if(name.length<2)return showMessage("Please enter your full name.");if(!/^\S+@\S+\.\S+$/.test(email))return showMessage("Please enter a valid email address.");if(p.length<6)return showMessage("Password must be at least 6 characters.");if(p!==c)return showMessage("Passwords do not match.");loading(true);try{const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password:p})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.success)throw new Error(data.message||"Registration failed.");saveAuth(data);showMessage("Account created successfully. Redirecting to ShopHub...","success");setTimeout(()=>location.href="../shop/index.html",700)}catch(err){showMessage(err.message||"Unable to create account.")}finally{loading(false)}});
